import crypto from "node:crypto";

const ALGORITHM = "aes-256-gcm";
const IV_LENGTH = 12; // 96-bit IV — the size AES-GCM is designed and recommended for
const AUTH_TAG_LENGTH = 16;

/**
 * AES-256-GCM using the installer's already-provisioned `ENCRYPTION_KEY`
 * (generated by Phase 1's security.service.ts, written to `.env` with 0600
 * permissions — see docs/SECURITY.md). Reuses that key rather than
 * minting a second one, so there's exactly one encryption secret for the
 * whole product to protect and rotate.
 */
function getKey(): Buffer {
  const hex = process.env.ENCRYPTION_KEY;
  if (!hex) {
    throw new Error("ENCRYPTION_KEY is not set — this is generated by the installer into .env and must be present before encrypting or decrypting anything.");
  }
  const key = Buffer.from(hex, "hex");
  if (key.length !== 32) {
    throw new Error(`ENCRYPTION_KEY must decode to 32 bytes for AES-256 (got ${key.length})`);
  }
  return key;
}

/**
 * Encrypts a UTF-8 string, returning one self-contained base64 payload
 * (iv || authTag || ciphertext) — safe to store as a single opaque column
 * value. GCM's auth tag makes tampering detectable: `decrypt` throws
 * rather than silently returning corrupted plaintext if the payload was
 * altered.
 */
export function encrypt(plaintext: string): string {
  const key = getKey();
  const iv = crypto.randomBytes(IV_LENGTH);
  const cipher = crypto.createCipheriv(ALGORITHM, key, iv);
  const ciphertext = Buffer.concat([cipher.update(plaintext, "utf-8"), cipher.final()]);
  const authTag = cipher.getAuthTag();
  return Buffer.concat([iv, authTag, ciphertext]).toString("base64");
}

/** Decrypts a payload produced by `encrypt`. Throws if ENCRYPTION_KEY is wrong or the payload was tampered with/corrupted (GCM authentication failure). */
export function decrypt(payload: string): string {
  const key = getKey();
  const raw = Buffer.from(payload, "base64");
  if (raw.length < IV_LENGTH + AUTH_TAG_LENGTH) {
    throw new Error("Encrypted payload is too short to be valid");
  }
  const iv = raw.subarray(0, IV_LENGTH);
  const authTag = raw.subarray(IV_LENGTH, IV_LENGTH + AUTH_TAG_LENGTH);
  const ciphertext = raw.subarray(IV_LENGTH + AUTH_TAG_LENGTH);

  const decipher = crypto.createDecipheriv(ALGORITHM, key, iv);
  decipher.setAuthTag(authTag);
  const plaintext = Buffer.concat([decipher.update(ciphertext), decipher.final()]);
  return plaintext.toString("utf-8");
}
